version: "3.8"

services:
  db:
    container_name: learnbase-db-dev
    platform: linux/amd64
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - learnbase-dev

  backend:
    container_name: learnbase-backend-dev
    platform: linux/amd64
    build:
      context: ../backend
      dockerfile: ./Dockerfile.backend
    ports:
      - "3001:3001"
    volumes:
      - ../backend:/usr/app
      - /usr/app/node_modules
    environment:
      DATABASE_URL: ${DATABASE_URL}
      HASH_SALT: ${HASH_SALT}
    env_file:
      - .env
    networks:
      - learnbase-dev
    depends_on:
      - db

  admin-app:
    container_name: learnbase-admin-app-dev
    platform: linux/amd64
    build:
      context: ../admin-app
      dockerfile: ./Dockerfile.admin-app
    ports:
      - "3000:3000"
    volumes:
      - ../admin-app:/usr/app
      - /usr/app/node_modules
    environment:
      VITE_IS_DEV: ${VITE_IS_DEV}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    env_file:
      - .env
    networks:
      - learnbase-dev

  client-app:
    container_name: learnbase-client-app-dev
    platform: linux/amd64
    build:
      context: ../client-app
      dockerfile: ./Dockerfile.client-app
    ports:
      - "3002:3000"
    volumes:
      - ../client-app:/usr/app
      - /usr/app/node_modules
    environment:
      NEXT_PUBLIC_IS_DEV: ${NEXT_PUBLIC_IS_DEV}
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    env_file:
      - .env
    networks:
      - learnbase-dev

networks:
  learnbase-dev:
volumes:
  db:
